name: paperfold_list
description: "A Flutter widget library providing an expandable list view that
  folds in/out like paper"
version: 1.0.0
homepage: https://github.com/kay-af/paperfold_list

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
