name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Analyze package scores
        uses: flutterings/dart-package-analyzer@v1
        id: analysis

      - name: Check points
        env:
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        run: |
          echo "Points: $TOTAL/$TOTAL_MAX"
          if [ $TOTAL -lt $TOTAL_MAX ]; then
            echo "👎 Package is not fit for publishing."
            exit 1
          else
            echo "👍 Package is fit for publishing."
          fi
